# services: 
#   app:
#     build:
#       context: .
#     image: nextjs-dev
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: development

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"